server:
  port: 8080

druid:
  master:
    url: jdbc:mysql://localhost:3306/bbs?characterEncoding=utf8&useSSL=true&serverTimezone=Hongkong
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  slave:
      url: jdbc:mysql://localhost:3307/bbs?characterEncoding=utf8&useSSL=true&serverTimezone=Hongkong
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  mapperLocations: classpath*:mapping/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    interceptors: com.person.demo.config.DateSourceSelectInterceptor

mapper:
    mappers:
        - com.person.demo.util.TkMapper
    not-empty: false
    identity: MYSQL

