server:
  port: 8081


#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/bbs?characterEncoding=utf8&useSSL=true&serverTimezone=Hongkong
#    username: root
#    password: 123456
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    type: com.alibaba.druid.pool.DruidDataSource
#  jpa:
#    show-sql: true


druid:
  master:
    url: jdbc:mysql://localhost:3306/bbs?characterEncoding=utf8&useSSL=true&serverTimezone=Hongkong
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  slave:
      url: jdbc:mysql://localhost:3307/bbs?characterEncoding=utf8&useSSL=true&serverTimezone=Hongkong
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
spring:
  jpa:
    show-sql: true